---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
  namespace: dev
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-db
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-db
          image: mysql:8.2.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
          ports:
            - protocol: TCP
              containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: dev
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
